# Generated by Django 4.2.16 on 2024-11-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='노래 제목')),
                ('artist', models.CharField(max_length=100, verbose_name='가수')),
                ('lowest_note', models.CharField(max_length=3, verbose_name='최저음')),
                ('highest_note', models.CharField(max_length=3, verbose_name='최고음')),
            ],
            options={
                'verbose_name': '노래',
                'verbose_name_plural': '노래들',
            },
        ),
    ]
